services:
  lab_inteligencia:
    image: lab_inteligencia 
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pioneer 
    network_mode: host
    devices:
      - /dev/pioneer:/dev/pioneer
      - /dev/joy:/dev/joy
      - /dev/event_joy:/dev/event_joy
      - /dev/video0:/dev/video0
    environment:
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - CYCLONEDDS_URI=file:///cyclonedds.xml
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    stdin_open: true
    tty: true
