services:
  lab_inteligencia:
    image: lab_inteligencia 
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pioneer 
    network_mode: host
    volumes:
      - ~/Documents/proyecto_el5206/football_player:/home/bender_ws/src/proyecto_el5206/football_player
    devices:
      - /dev/pioneer:/dev/pioneer
      - /dev/joy:/dev/joy
      - /dev/event_joy:/dev/event_joy
      - /dev/video4:/dev/video4
      - /dev/video5:/dev/video5
      - /dev/media2:/dev/media2

    environment:
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - CYCLONEDDS_URI=file:///cyclonedds.xml
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    stdin_open: true
    tty: true
