services:
  blender_gen:
    image: blender_gen
    build:
      context: .
      dockerfile: Dockerfile
    container_name: blender_gen_container
    working_dir: /home/amtc_ws
    volumes:
      - ~/Documents/data:/home/amtc_ws/data
      - ~/Documents/mujoco_assets:/home/amtc_ws/mujoco_assets
      - ~/Documents/blendgen:/blendgen
      - ~/Documents/test:/home/amtc_ws/test
    environment:
      - DISPLAY=:1
    stdin_open: true
    tty: true
