services:
  jax_mjx_madrona_container:
    image: jax_mjx_madrona
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jax_mjx_madrona_container
    working_dir: /home/amtc_ws
    volumes:
      - ~/Documents/test:/home/amtc_ws/test
      - ~/Documents/mujoco_assets:/home/amtc_ws/mujoco_assets
    environment:
      - DISPLAY=:1
    stdin_open: true
    tty: true
